version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./app:/app
    links:
      - php-fpm

  php-fpm:
    image: infinight/php-fpm
    volumes:
      - ./app:/app
    links:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=test123
    ports:
      - "3306:3306"
    volumes:
      - ./storages/mysql:/var/lib/mysql
